/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 
 * ubs-hcom is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *      http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#ifndef HCOM_TRACE_H
#define HCOM_TRACE_H

#include <mutex>
#include <iomanip>
#include <sstream>
#include <functional>
#include "hcom_def.h"
#include "hcom_utils.h"
#include "trace/htracer.h"

namespace ock {
namespace hcom {
#define GENERATE_TRACE_ID(level, innerId) ((level) << NN_NO24 | ((innerId)&0xFFFFFF))

enum NetTraceLevel : uint8_t {
    LEVEL0 = 0, // disable
    LEVEL1,     // High priority , LEVEL1 enable
    LEVEL2,     // Middle priority, LEVEL1 + LEVEL2 enable
    LEVEL3,     // Low priority , LEVEL1 + LEVEL2+LEVEL3 enable
};

enum NetTracePointId : uint32_t {
    SERVICE_INSTANCE_INNER = 0,
    SERVICE_START_INNER,
    SERVICE_STOP_INNER,
    SERVICE_CONNECT_DO_INNER,
    SERVICE_RECONNECT_DO_INNER,
    SERVICE_RECONNECT_COMFIRM_INNER,
    SERVICE_REG_MR_INNER,
    SERVICE_REG_MR_WITH_PTR_INNER,
    SERVICE_DESTROY_MR_INNER,
    SERVICE_OP_HANDLE_RNDV_INNER,
    SERVICE_OP_HANDLE_RNDV_SGL_INNER,
    SERVICE_OP_HANDLE_RECONNECT_INNER,
    SERVICE_CB_REQUEST_RECEIVED_INNER,
    SERVICE_CB_REQUEST_POSTED_INNER,
    SERVICE_CB_ONESIDE_DONE_INNER,
    SERVICE_CB_NEW_CHANNEL_INNER,
    SERVICE_CB_BROKEN_CHANNEL_INNER,
    SERVICE_THREAD_PERIODIC_INNER,

    CHANNEL_SEND_INNER,
    CHANNEL_SEND_RAW_INNER,
    CHANNEL_SEND_RAW_SGL_INNER,
    CHANNEL_SYNC_CALL_INNER,
    CHANNEL_ASYNC_CALL_INNER,
    CHANNEL_SYNC_CALL_RAW_INNER,
    CHANNEL_ASYNC_CALL_RAW_INNER,
    CHANNEL_SYNC_CALL_RAW_SGL_INNER,
    CHANNEL_ASYNC_CALL_RAW_SGL_INNER,
    CHANNEL_SYNC_RNDV_CALL_INNER,
    CHANNEL_ASYNC_RNDV_CALL_INNER,
    CHANNEL_SYNC_RNDV_SGL_CALL_INNER,
    CHANNEL_ASYNC_RNDV_SGL_CALL_INNER,
    CHANNEL_READ_INNER,
    CHANNEL_READ_SGL_INNER,
    CHANNEL_WRITE_INNER,
    CHANNEL_WRITE_SGL_INNER,
    CHANNEL_SEND_FD_INNER,
    CHANNEL_RECEIVE_FD_INNER,

    RDMA_DRIVER_INIT_INNER,
    RDMA_DRIVER_UNINIT_INNER,
    RDMA_DRIVER_START_INNER,
    RDMA_DRIVER_STOP_INNER,
    RDMA_DRIVER_CONNECT_EP_INNER,
    RDMA_DRIVER_DESTROY_EP_INNER,
    RDMA_THREAD_HEARTBEAT_INNER,
    RDMA_THREAD_ASYNC_EVENT_INNER,
    RDMA_WORKER_BUSY_POLLING_INNER,
    RDMA_WORKER_EVENT_POLLING_INNER,
    RDMA_EP_ASYNC_POST_SEND_INNER,
    RDMA_EP_ASYNC_POST_SEND_RAW_INNER,
    RDMA_EP_ASYNC_POST_SEND_RAW_SGL_INNER,
    RDMA_EP_ASYNC_POST_READ_INNER,
    RDMA_EP_ASYNC_POST_READ_SGL_INNER,
    RDMA_EP_ASYNC_POST_WRITE_INNER,
    RDMA_EP_ASYNC_POST_WRITE_SGL_INNER,
    RDMA_EP_SYNC_POST_SEND_INNER,
    RDMA_EP_SYNC_POST_SEND_RAW_INNER,
    RDMA_EP_SYNC_POST_SEND_RAW_SGL_INNER,
    RDMA_EP_SYNC_POST_READ_INNER,
    RDMA_EP_SYNC_POST_READ_SGL_INNER,
    RDMA_EP_SYNC_POST_WRITE_INNER,
    RDMA_EP_SYNC_POST_WRITE_SGL_INNER,
    RDMA_EP_SYNC_RECEIVE_INNER,
    RDMA_EP_SYNC_WAIT_COMPLETION_INNER,

    SOCK_DRIVER_CONNECT_INNER,
    SOCK_DRIVER_HANDLE_CONNECT_INNER,
    SOCK_DRIVER_INITIALIZE_INNER,
    SOCK_DRIVER_START_INNER,
    SOCK_DRIVER_CREATE_WORKER_RESOURCE_INNER,
    SOCK_DRIVER_CREATE_WORKERS_INNER,
    SOCK_DRIVER_CREATE_CLIENT_LB_INNER,
    SOCK_DRIVER_CREATE_LISTENERS_INNER,
    SOCK_DRIVER_WORKER_START_INNER,
    SOCK_DRIVER_START_LISTENERS_INNER,
    SOCK_WORKER_EPOLL_WAIT_INNER,
    SOCK_WORKER_HANDLE_EVENT_INNER,
    SOCK_WORKER_HANDLE_EPOLLIN_EVENT_INNER,
    SOCK_WORKER_HANDLE_EPOLL_OUT_EVENT_INNER,
    SOCK_WORKER_HANDLE_EPOLL_WRNORM_EVENT_INNER,
    SOCK_WORKER_IDLE_HANDLER_INNER,
    SOCK_EP_BLOCK_POST_SEND_INNER,
    SOCK_EP_ASYNC_POST_SEND_INNER,
    SOCK_EP_ASYNC_POST_SEND_RAW_INNER,
    SOCK_EP_ASYNC_POST_SEND_RAW_SGL_INNER,
    SOCK_EP_ASYNC_POST_READ_INNER,
    SOCK_EP_ASYNC_POST_READ_SGL_INNER,
    SOCK_EP_ASYNC_POST_WRITE_INNER,
    SOCK_EP_ASYNC_POST_WRITE_SGL_INNER,
    SOCK_EP_SYNC_POST_SEND_INNER,
    SOCK_EP_SYNC_POST_SEND_RAW_INNER,
    SOCK_EP_SYNC_POST_SEND_RAW_SGL_INNER,
    SOCK_EP_SYNC_POST_READ_INNER,
    SOCK_EP_SYNC_POST_READ_SGL_INNER,
    SOCK_EP_SYNC_POST_WRITE_INNER,
    SOCK_EP_SYNC_POST_WRITE_SGL_INNER,
    SOCK_EP_SYNC_RECEIVE_INNER,
    SOCK_EP_SYNC_WAIT_COMPLETION_INNER,

    SHM_DRIVER_INIT_INNER,
    SHM_DRIVER_UNINIT_INNER,
    SHM_DRIVER_START_INNER,
    SHM_DRIVER_STOP_INNER,
    SHM_DRIVER_CONNECT_INNER,
    SHM_DRIVER_CREATE_MEMORY_REGION_INNER,
    SHM_DRIVER_DESTORY_MEMORY_REGION_INNER,
    SHM_WORKER_BUSY_POLLING_INNER,
    SHM_WORKER_EVENT_POLLING_INNER,
    SHM_THREAD_CHANNEL_KEEPER_INNER,
    SHM_EP_ASYNC_POST_SEND_INNER,
    SHM_EP_ASYNC_POST_SEND_RAW_INNER,
    SHM_EP_ASYNC_POST_SEND_RAW_SGL_INNER,
    SHM_EP_ASYNC_POST_READ_INNER,
    SHM_EP_ASYNC_POST_READ_SGL_INNER,
    SHM_EP_ASYNC_POST_WRITE_INNER,
    SHM_EP_ASYNC_POST_WRITE_SGL_INNER,
    SHM_EP_ASYNC_SEND_FDS_INNER,
    SHM_EP_ASYNC_RECEIVE_FDS_INNER,
    SHM_EP_SYNC_POST_SEND_INNER,
    SHM_EP_SYNC_POST_SEND_RAW_INNER,
    SHM_EP_SYNC_POST_SEND_RAW_SGL_INNER,
    SHM_EP_SYNC_POST_READ_INNER,
    SHM_EP_SYNC_POST_READ_SGL_INNER,
    SHM_EP_SYNC_POST_WRITE_INNER,
    SHM_EP_SYNC_POST_WRITE_SGL_INNER,
    SHM_EP_SYNC_WAIT_COMPLETION_INNER,
    SHM_EP_SYNC_RECEIVE_INNER,
    SHM_EP_SYNC_RECEIVE_RAW_INNER,

    UB_WORKER_BUSY_POLLING_INNER,
    UB_WORKER_EVENT_POLLING_INNER,
    UB_EP_ASYNC_POST_SEND_INNER,
    UB_EP_ASYNC_POST_SEND_RAW_INNER,
    UB_EP_ASYNC_POST_SEND_RAW_SGL_INNER,
    UB_EP_ASYNC_POST_READ_INNER,
    UB_EP_ASYNC_POST_READ_SGL_INNER,
    UB_EP_ASYNC_POST_WRITE_INNER,
    UB_EP_ASYNC_POST_WRITE_SGL_INNER,
    UB_EP_SYNC_POST_SEND_INNER,
    UB_EP_SYNC_POST_SEND_RAW_INNER,
    UB_EP_SYNC_POST_SEND_RAW_SGL_INNER,
    UB_EP_SYNC_POST_READ_INNER,
    UB_EP_SYNC_POST_READ_SGL_INNER,
    UB_EP_SYNC_POST_WRITE_INNER,
    UB_EP_SYNC_POST_WRITE_SGL_INNER,

    OOB_START_INNER,
    OOB_STOP_INNER,
    OOB_CONN_SEND_INNER,
    OOB_CONN_RECEIVE_INNER,
    OOB_CONN_SEND_MSG_INNER,
    OOB_CONN_RECEIVE_MSG_INNER,
    OOB_ACCREPT_SOCKET_INNER,
    OOB_CONNECT_SOCKET_INNER,
    OOB_EXEC_CONN_TASK_INNER,
    OOB_SECINFO_PROVIDER_INNER,
    OOB_SECINFO_VALIDATOR_INNER,

    SERVICE_IO_BROKEN_CALLBACK_INNER,
    SERVICE_POSTED_OR_DONE_CALLBACK_INNER,
    SERVICE_CALL_DONE_CALLBACK_INNER,
    SERVICE_RUN_CALLBACK_INNER,
    TIMEOUT_RUN_CALLBACK_INNER,

    MAX_MODULE_ID_INNER,
};

enum NetTracePointIdWithLevel : uint32_t {
    SERVICE_INSTANCE = TRACE_ID(SERVICE_INSTANCE_INNER, LEVEL1),
    SERVICE_START = TRACE_ID(SERVICE_START_INNER, LEVEL1),
    SERVICE_STOP = TRACE_ID(SERVICE_STOP_INNER, LEVEL1),
    SERVICE_CONNECT_DO = TRACE_ID(SERVICE_CONNECT_DO_INNER, LEVEL1),
    SERVICE_RECONNECT_DO = TRACE_ID(SERVICE_RECONNECT_DO_INNER, LEVEL1),
    SERVICE_RECONNECT_COMFIRM = TRACE_ID(SERVICE_RECONNECT_COMFIRM_INNER, LEVEL1),
    SERVICE_REG_MR = TRACE_ID(SERVICE_REG_MR_INNER, LEVEL1),
    SERVICE_REG_MR_WITH_PTR = TRACE_ID(SERVICE_REG_MR_WITH_PTR_INNER, LEVEL1),
    SERVICE_DESTROY_MR = TRACE_ID(SERVICE_DESTROY_MR_INNER, LEVEL1),
    SERVICE_OP_HANDLE_RNDV = TRACE_ID(SERVICE_OP_HANDLE_RNDV_INNER, LEVEL1),
    SERVICE_OP_HANDLE_RNDV_SGL = TRACE_ID(SERVICE_OP_HANDLE_RNDV_SGL_INNER, LEVEL1),
    SERVICE_OP_HANDLE_RECONNECT = TRACE_ID(SERVICE_OP_HANDLE_RECONNECT_INNER, LEVEL1),
    SERVICE_CB_REQUEST_RECEIVED = TRACE_ID(SERVICE_CB_REQUEST_RECEIVED_INNER, LEVEL1),
    SERVICE_CB_REQUEST_POSTED = TRACE_ID(SERVICE_CB_REQUEST_POSTED_INNER, LEVEL1),
    SERVICE_CB_ONESIDE_DONE = TRACE_ID(SERVICE_CB_ONESIDE_DONE_INNER, LEVEL1),
    SERVICE_CB_NEW_CHANNEL = TRACE_ID(SERVICE_CB_NEW_CHANNEL_INNER, LEVEL1),
    SERVICE_CB_BROKEN_CHANNEL = TRACE_ID(SERVICE_CB_BROKEN_CHANNEL_INNER, LEVEL1),
    SERVICE_THREAD_PERIODIC = TRACE_ID(SERVICE_THREAD_PERIODIC_INNER, LEVEL1),

    // CHANNEL_SEND = TRACE_ID(CHANNEL_SEND_INNER, LEVEL1),
    CHANNEL_SEND = TRACE_ID(CHANNEL_SEND_INNER, LEVEL1),
    CHANNEL_SEND_RAW = TRACE_ID(CHANNEL_SEND_RAW_INNER, LEVEL1),
    CHANNEL_SEND_RAW_SGL = TRACE_ID(CHANNEL_SEND_RAW_SGL_INNER, LEVEL1),
    CHANNEL_SYNC_CALL = TRACE_ID(CHANNEL_SYNC_CALL_INNER, LEVEL1),
    CHANNEL_ASYNC_CALL = TRACE_ID(CHANNEL_ASYNC_CALL_INNER, LEVEL1),
    CHANNEL_SYNC_CALL_RAW = TRACE_ID(CHANNEL_SYNC_CALL_RAW_INNER, LEVEL1),
    CHANNEL_ASYNC_CALL_RAW = TRACE_ID(CHANNEL_ASYNC_CALL_RAW_INNER, LEVEL1),
    CHANNEL_SYNC_CALL_RAW_SGL = TRACE_ID(CHANNEL_SYNC_CALL_RAW_SGL_INNER, LEVEL1),
    CHANNEL_ASYNC_CALL_RAW_SGL = TRACE_ID(CHANNEL_ASYNC_CALL_RAW_SGL_INNER, LEVEL1),
    CHANNEL_SYNC_RNDV_CALL = TRACE_ID(CHANNEL_SYNC_RNDV_CALL_INNER, LEVEL1),
    CHANNEL_ASYNC_RNDV_CALL = TRACE_ID(CHANNEL_ASYNC_RNDV_CALL_INNER, LEVEL1),
    CHANNEL_SYNC_RNDV_SGL_CALL = TRACE_ID(CHANNEL_SYNC_RNDV_SGL_CALL_INNER, LEVEL1),
    CHANNEL_ASYNC_RNDV_SGL_CALL = TRACE_ID(CHANNEL_ASYNC_RNDV_SGL_CALL_INNER, LEVEL1),
    CHANNEL_READ = TRACE_ID(CHANNEL_READ_INNER, LEVEL1),
    CHANNEL_READ_SGL = TRACE_ID(CHANNEL_READ_SGL_INNER, LEVEL1),
    CHANNEL_WRITE = TRACE_ID(CHANNEL_WRITE_INNER, LEVEL1),
    CHANNEL_WRITE_SGL = TRACE_ID(CHANNEL_WRITE_SGL_INNER, LEVEL1),
    CHANNEL_SEND_FD = TRACE_ID(CHANNEL_SEND_FD_INNER, LEVEL1),
    CHANNEL_RECEIVE_FD = TRACE_ID(CHANNEL_RECEIVE_FD_INNER, LEVEL1),

    RDMA_DRIVER_INIT = TRACE_ID(RDMA_DRIVER_INIT_INNER, LEVEL1),
    RDMA_DRIVER_UNINIT = TRACE_ID(RDMA_DRIVER_UNINIT_INNER, LEVEL1),
    RDMA_DRIVER_START = TRACE_ID(RDMA_DRIVER_START_INNER, LEVEL1),
    RDMA_DRIVER_STOP = TRACE_ID(RDMA_DRIVER_STOP_INNER, LEVEL1),
    RDMA_DRIVER_CONNECT_EP = TRACE_ID(RDMA_DRIVER_CONNECT_EP_INNER, LEVEL1),
    RDMA_DRIVER_DESTROY_EP = TRACE_ID(RDMA_DRIVER_DESTROY_EP_INNER, LEVEL1),
    RDMA_THREAD_HEARTBEAT = TRACE_ID(RDMA_THREAD_HEARTBEAT_INNER, LEVEL1),
    RDMA_THREAD_ASYNC_EVENT = TRACE_ID(RDMA_THREAD_ASYNC_EVENT_INNER, LEVEL1),
    RDMA_WORKER_BUSY_POLLING = TRACE_ID(RDMA_WORKER_BUSY_POLLING_INNER, LEVEL1),
    RDMA_WORKER_EVENT_POLLING = TRACE_ID(RDMA_WORKER_EVENT_POLLING_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_SEND = TRACE_ID(RDMA_EP_ASYNC_POST_SEND_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_SEND_RAW = TRACE_ID(RDMA_EP_ASYNC_POST_SEND_RAW_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_SEND_RAW_SGL = TRACE_ID(RDMA_EP_ASYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_READ = TRACE_ID(RDMA_EP_ASYNC_POST_READ_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_READ_SGL = TRACE_ID(RDMA_EP_ASYNC_POST_READ_SGL_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_WRITE = TRACE_ID(RDMA_EP_ASYNC_POST_WRITE_INNER, LEVEL1),
    RDMA_EP_ASYNC_POST_WRITE_SGL = TRACE_ID(RDMA_EP_ASYNC_POST_WRITE_SGL_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_SEND = TRACE_ID(RDMA_EP_SYNC_POST_SEND_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_SEND_RAW = TRACE_ID(RDMA_EP_SYNC_POST_SEND_RAW_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_SEND_RAW_SGL = TRACE_ID(RDMA_EP_SYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_READ = TRACE_ID(RDMA_EP_SYNC_POST_READ_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_READ_SGL = TRACE_ID(RDMA_EP_SYNC_POST_READ_SGL_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_WRITE = TRACE_ID(RDMA_EP_SYNC_POST_WRITE_INNER, LEVEL1),
    RDMA_EP_SYNC_POST_WRITE_SGL = TRACE_ID(RDMA_EP_SYNC_POST_WRITE_SGL_INNER, LEVEL1),
    RDMA_EP_SYNC_RECEIVE = TRACE_ID(RDMA_EP_SYNC_RECEIVE_INNER, LEVEL1),
    RDMA_EP_SYNC_WAIT_COMPLETION = TRACE_ID(RDMA_EP_SYNC_WAIT_COMPLETION_INNER, LEVEL1),

    SOCK_DRIVER_CONNECT = TRACE_ID(SOCK_DRIVER_CONNECT_INNER, LEVEL1),
    SOCK_DRIVER_HANDLE_CONNECT = TRACE_ID(SOCK_DRIVER_HANDLE_CONNECT_INNER, LEVEL1),
    SOCK_DRIVER_INITIALIZE = TRACE_ID(SOCK_DRIVER_INITIALIZE_INNER, LEVEL1),
    SOCK_DRIVER_START = TRACE_ID(SOCK_DRIVER_START_INNER, LEVEL1),
    SOCK_DRIVER_CREATE_WORKER_RESOURCE = TRACE_ID(SOCK_DRIVER_CREATE_WORKER_RESOURCE_INNER, LEVEL1),
    SOCK_DRIVER_CREATE_WORKERS = TRACE_ID(SOCK_DRIVER_CREATE_WORKERS_INNER, LEVEL1),
    SOCK_DRIVER_CREATE_CLIENT_LB = TRACE_ID(SOCK_DRIVER_CREATE_CLIENT_LB_INNER, LEVEL1),
    SOCK_DRIVER_CREATE_LISTENERS = TRACE_ID(SOCK_DRIVER_CREATE_LISTENERS_INNER, LEVEL1),
    SOCK_DRIVER_WORKER_START = TRACE_ID(SOCK_DRIVER_WORKER_START_INNER, LEVEL1),
    SOCK_DRIVER_START_LISTENERS = TRACE_ID(SOCK_DRIVER_START_LISTENERS_INNER, LEVEL1),
    SOCK_WORKER_EPOLL_WAIT = TRACE_ID(SOCK_WORKER_EPOLL_WAIT_INNER, LEVEL1),
    SOCK_WORKER_HANDLE_EVENT = TRACE_ID(SOCK_WORKER_HANDLE_EVENT_INNER, LEVEL1),
    SOCK_WORKER_HANDLE_EPOLLIN_EVENT = TRACE_ID(SOCK_WORKER_HANDLE_EPOLLIN_EVENT_INNER, LEVEL1),
    SOCK_WORKER_HANDLE_EPOLL_OUT_EVENT = TRACE_ID(SOCK_WORKER_HANDLE_EPOLL_OUT_EVENT_INNER, LEVEL1),
    SOCK_WORKER_HANDLE_EPOLL_WRNORM_EVENT = TRACE_ID(SOCK_WORKER_HANDLE_EPOLL_WRNORM_EVENT_INNER, LEVEL1),
    SOCK_WORKER_IDLE_HANDLER = TRACE_ID(SOCK_WORKER_IDLE_HANDLER_INNER, LEVEL1),
    SOCK_EP_BLOCK_POST_SEND = TRACE_ID(SOCK_EP_BLOCK_POST_SEND_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_SEND = TRACE_ID(SOCK_EP_ASYNC_POST_SEND_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_SEND_RAW = TRACE_ID(SOCK_EP_ASYNC_POST_SEND_RAW_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_SEND_RAW_SGL = TRACE_ID(SOCK_EP_ASYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_READ = TRACE_ID(SOCK_EP_ASYNC_POST_READ_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_READ_SGL = TRACE_ID(SOCK_EP_ASYNC_POST_READ_SGL_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_WRITE = TRACE_ID(SOCK_EP_ASYNC_POST_WRITE_INNER, LEVEL1),
    SOCK_EP_ASYNC_POST_WRITE_SGL = TRACE_ID(SOCK_EP_ASYNC_POST_WRITE_SGL_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_SEND = TRACE_ID(SOCK_EP_SYNC_POST_SEND_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_SEND_RAW = TRACE_ID(SOCK_EP_SYNC_POST_SEND_RAW_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_SEND_RAW_SGL = TRACE_ID(SOCK_EP_SYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_READ = TRACE_ID(SOCK_EP_SYNC_POST_READ_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_READ_SGL = TRACE_ID(SOCK_EP_SYNC_POST_READ_SGL_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_WRITE = TRACE_ID(SOCK_EP_SYNC_POST_WRITE_INNER, LEVEL1),
    SOCK_EP_SYNC_POST_WRITE_SGL = TRACE_ID(SOCK_EP_SYNC_POST_WRITE_SGL_INNER, LEVEL1),
    SOCK_EP_SYNC_RECEIVE = TRACE_ID(SOCK_EP_SYNC_RECEIVE_INNER, LEVEL1),
    SOCK_EP_SYNC_WAIT_COMPLETION = TRACE_ID(SOCK_EP_SYNC_WAIT_COMPLETION_INNER, LEVEL1),

    SHM_DRIVER_INIT = TRACE_ID(SHM_DRIVER_INIT_INNER, LEVEL1),
    SHM_DRIVER_UNINIT = TRACE_ID(SHM_DRIVER_UNINIT_INNER, LEVEL1),
    SHM_DRIVER_START = TRACE_ID(SHM_DRIVER_START_INNER, LEVEL1),
    SHM_DRIVER_STOP = TRACE_ID(SHM_DRIVER_STOP_INNER, LEVEL1),
    SHM_DRIVER_CONNECT = TRACE_ID(SHM_DRIVER_CONNECT_INNER, LEVEL1),
    SHM_DRIVER_CREATE_MEMORY_REGION = TRACE_ID(SHM_DRIVER_CREATE_MEMORY_REGION_INNER, LEVEL1),
    SHM_DRIVER_DESTORY_MEMORY_REGION = TRACE_ID(SHM_DRIVER_DESTORY_MEMORY_REGION_INNER, LEVEL1),
    SHM_WORKER_BUSY_POLLING = TRACE_ID(SHM_WORKER_BUSY_POLLING_INNER, LEVEL1),
    SHM_WORKER_EVENT_POLLING = TRACE_ID(SHM_WORKER_EVENT_POLLING_INNER, LEVEL1),
    SHM_THREAD_CHANNEL_KEEPER = TRACE_ID(SHM_THREAD_CHANNEL_KEEPER_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_SEND = TRACE_ID(SHM_EP_ASYNC_POST_SEND_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_SEND_RAW = TRACE_ID(SHM_EP_ASYNC_POST_SEND_RAW_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_SEND_RAW_SGL = TRACE_ID(SHM_EP_ASYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_READ = TRACE_ID(SHM_EP_ASYNC_POST_READ_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_READ_SGL = TRACE_ID(SHM_EP_ASYNC_POST_READ_SGL_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_WRITE = TRACE_ID(SHM_EP_ASYNC_POST_WRITE_INNER, LEVEL1),
    SHM_EP_ASYNC_POST_WRITE_SGL = TRACE_ID(SHM_EP_ASYNC_POST_WRITE_SGL_INNER, LEVEL1),
    SHM_EP_ASYNC_SEND_FDS = TRACE_ID(SHM_EP_ASYNC_SEND_FDS_INNER, LEVEL1),
    SHM_EP_ASYNC_RECEIVE_FDS = TRACE_ID(SHM_EP_ASYNC_RECEIVE_FDS_INNER, LEVEL1),
    SHM_EP_SYNC_POST_SEND = TRACE_ID(SHM_EP_SYNC_POST_SEND_INNER, LEVEL1),
    SHM_EP_SYNC_POST_SEND_RAW = TRACE_ID(SHM_EP_SYNC_POST_SEND_RAW_INNER, LEVEL1),
    SHM_EP_SYNC_POST_SEND_RAW_SGL = TRACE_ID(SHM_EP_SYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    SHM_EP_SYNC_POST_READ = TRACE_ID(SHM_EP_SYNC_POST_READ_INNER, LEVEL1),
    SHM_EP_SYNC_POST_READ_SGL = TRACE_ID(SHM_EP_SYNC_POST_READ_SGL_INNER, LEVEL1),
    SHM_EP_SYNC_POST_WRITE = TRACE_ID(SHM_EP_SYNC_POST_WRITE_INNER, LEVEL1),
    SHM_EP_SYNC_POST_WRITE_SGL = TRACE_ID(SHM_EP_SYNC_POST_WRITE_SGL_INNER, LEVEL1),
    SHM_EP_SYNC_WAIT_COMPLETION = TRACE_ID(SHM_EP_SYNC_WAIT_COMPLETION_INNER, LEVEL1),
    SHM_EP_SYNC_RECEIVE = TRACE_ID(SHM_EP_SYNC_RECEIVE_INNER, LEVEL1),
    SHM_EP_SYNC_RECEIVE_RAW = TRACE_ID(SHM_EP_SYNC_RECEIVE_RAW_INNER, LEVEL1),

    UB_WORKER_BUSY_POLLING = TRACE_ID(UB_WORKER_BUSY_POLLING_INNER, LEVEL1),
    UB_WORKER_EVENT_POLLING = TRACE_ID(UB_WORKER_EVENT_POLLING_INNER, LEVEL1),
    UB_EP_ASYNC_POST_SEND = TRACE_ID(UB_EP_ASYNC_POST_SEND_INNER, LEVEL1),
    UB_EP_ASYNC_POST_SEND_RAW = TRACE_ID(UB_EP_ASYNC_POST_SEND_RAW_INNER, LEVEL1),
    UB_EP_ASYNC_POST_SEND_RAW_SGL = TRACE_ID(UB_EP_ASYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    UB_EP_ASYNC_POST_READ = TRACE_ID(UB_EP_ASYNC_POST_READ_INNER, LEVEL1),
    UB_EP_ASYNC_POST_READ_SGL = TRACE_ID(UB_EP_ASYNC_POST_READ_SGL_INNER, LEVEL1),
    UB_EP_ASYNC_POST_WRITE = TRACE_ID(UB_EP_ASYNC_POST_WRITE_INNER, LEVEL1),
    UB_EP_ASYNC_POST_WRITE_SGL = TRACE_ID(UB_EP_ASYNC_POST_WRITE_SGL_INNER, LEVEL1),
    UB_EP_SYNC_POST_SEND = TRACE_ID(UB_EP_SYNC_POST_SEND_INNER, LEVEL1),
    UB_EP_SYNC_POST_SEND_RAW = TRACE_ID(UB_EP_SYNC_POST_SEND_RAW_INNER, LEVEL1),
    UB_EP_SYNC_POST_SEND_RAW_SGL = TRACE_ID(UB_EP_SYNC_POST_SEND_RAW_SGL_INNER, LEVEL1),
    UB_EP_SYNC_POST_READ = TRACE_ID(UB_EP_SYNC_POST_READ_INNER, LEVEL1),
    UB_EP_SYNC_POST_READ_SGL = TRACE_ID(UB_EP_SYNC_POST_READ_SGL_INNER, LEVEL1),
    UB_EP_SYNC_POST_WRITE = TRACE_ID(UB_EP_SYNC_POST_WRITE_INNER, LEVEL1),
    UB_EP_SYNC_POST_WRITE_SGL = TRACE_ID(UB_EP_SYNC_POST_WRITE_SGL_INNER, LEVEL1),

    OOB_START = TRACE_ID(OOB_START_INNER, LEVEL1),
    OOB_STOP = TRACE_ID(OOB_STOP_INNER, LEVEL1),
    OOB_CONN_SEND = TRACE_ID(OOB_CONN_SEND_INNER, LEVEL1),
    OOB_CONN_RECEIVE = TRACE_ID(OOB_CONN_RECEIVE_INNER, LEVEL1),
    OOB_CONN_SEND_MSG = TRACE_ID(OOB_CONN_SEND_MSG_INNER, LEVEL1),
    OOB_CONN_RECEIVE_MSG = TRACE_ID(OOB_CONN_RECEIVE_MSG_INNER, LEVEL1),
    OOB_ACCREPT_SOCKET = TRACE_ID(OOB_ACCREPT_SOCKET_INNER, LEVEL1),
    OOB_CONNECT_SOCKET = TRACE_ID(OOB_CONNECT_SOCKET_INNER, LEVEL1),
    OOB_EXEC_CONN_TASK = TRACE_ID(OOB_EXEC_CONN_TASK_INNER, LEVEL1),
    OOB_SECINFO_PROVIDER = TRACE_ID(OOB_SECINFO_PROVIDER_INNER, LEVEL1),
    OOB_SECINFO_VALIDATOR = TRACE_ID(OOB_SECINFO_VALIDATOR_INNER, LEVEL1),

    SERVICE_IO_BROKEN_CALLBACK = TRACE_ID(SERVICE_IO_BROKEN_CALLBACK_INNER, LEVEL1),
    SERVICE_POSTED_OR_DONE_CALLBACK = TRACE_ID(SERVICE_POSTED_OR_DONE_CALLBACK_INNER, LEVEL1),
    SERVICE_CALL_DONE_CALLBACK = TRACE_ID(SERVICE_CALL_DONE_CALLBACK_INNER, LEVEL1),
    SERVICE_RUN_CALLBACK = TRACE_ID(SERVICE_RUN_CALLBACK_INNER, LEVEL1),
    TIMEOUT_RUN_CALLBACK = TRACE_ID(TIMEOUT_RUN_CALLBACK_INNER, LEVEL1),
};

struct NetTraceItem {
    uint64_t count = 0;
    uint64_t success = 0;
    uint64_t fail = 0;
    uint64_t latency = 0;
    uint64_t maxLatency = 0;
    uint64_t minLatency = 0;
    uint64_t rsv1 = 0;
    uint64_t rsv2 = 0;
};

constexpr uint32_t BUCKET_MAX_SIZE = 32;
struct NetTracePoint {
    NetTraceItem mItem[BUCKET_MAX_SIZE] = {};
};

struct NetTracePointProperty {
    std::string name;       /* point name */
    uint64_t bucketIdx = 0; /* for different threads generate index by FAA */
};

class NetTrace {
public:
    static void HtraceInit(const std::string &name);

    static void Instance();

    NetTrace() = default;
    ~NetTrace() = default;

    void Initialize();

    __always_inline static void TraceBegin(uint32_t id)
    {
        if (NN_UNLIKELY(gTraceInst == nullptr)) {
            return;
        }

        auto level = Level(id);
        if (NN_UNLIKELY(level > gTraceInst->mEnableLevel)) {
            return;
        }

        auto item = gTraceInst->GetTraceItem(InnerId(id));
        __sync_fetch_and_add(&item->count, 1);
    }

    __always_inline static void TraceEnd(uint32_t id, int ret)
    {
        if (NN_UNLIKELY(gTraceInst == nullptr)) {
            return;
        }

        auto level = Level(id);
        if (NN_UNLIKELY(level > gTraceInst->mEnableLevel)) {
            return;
        }

        auto item = gTraceInst->GetTraceItem(InnerId(id));
        if (NN_LIKELY(ret == 0)) {
            __sync_fetch_and_add(&item->success, 1);
        } else {
            __sync_fetch_and_add(&item->fail, 1);
        }
    }

    static std::string TraceDump()
    {
        std::ostringstream ossDump;
        ossDump << std::endl;
        ossDump << std::setw(NN_NO48) << std::setiosflags(std::ios::left) << "Name";
        ossDump << std::setw(NN_NO32) << std::setiosflags(std::ios::left) << "Begin";
        ossDump << std::setw(NN_NO32) << std::setiosflags(std::ios::left) << "EndGood";
        ossDump << std::setw(NN_NO32) << std::setiosflags(std::ios::left) << "EndBad";
        ossDump << std::endl;

        if (NN_UNLIKELY(gTraceInst == nullptr)) {
            return ossDump.str();
        }

        for (uint32_t i = 0; i < MAX_MODULE_ID_INNER; i++) {
            struct NetTraceItem recordItem {};
            bzero(&recordItem, sizeof(recordItem));
            for (auto &j : gTraceInst->mPoint[i].mItem) {
                recordItem.count += __sync_fetch_and_add(&j.count, 0);
                recordItem.success += __sync_fetch_and_add(&j.success, 0);
                recordItem.fail += __sync_fetch_and_add(&j.fail, 0);
            }

            if (recordItem.count == 0) {
                /* ignore empty point */
                continue;
            }

            ossDump << std::setw(NN_NO48) << std::setiosflags(std::ios::left) << gTraceInst->mPointProperty[i].name;
            ossDump << std::setw(NN_NO32) << std::setiosflags(std::ios::left) << recordItem.count;
            ossDump << std::setw(NN_NO32) << std::setiosflags(std::ios::left) << recordItem.success;
            ossDump << std::setw(NN_NO32) << std::setiosflags(std::ios::left) << recordItem.fail;
            ossDump << std::endl;
        }
        return ossDump.str();
    }

private:
    __always_inline NetTraceItem *GetTraceItem(uint16_t innerId)
    {
        static thread_local auto itemIndex =
            __sync_fetch_and_add(&mPointProperty[innerId].bucketIdx, 1) % BUCKET_MAX_SIZE;

        return &mPoint[innerId].mItem[itemIndex];
    }

    static inline uint16_t Level(uint32_t id)
    {
        return (id >> NN_NO24) & 0xFF;
    }

    static inline uint16_t InnerId(uint32_t id)
    {
        return id & 0xFFFFFF;
    }

    NetTraceLevel mEnableLevel = LEVEL0;                       /* level switch for enable or not */
    NetTracePoint mPoint[MAX_MODULE_ID_INNER];                 /* trace point */
    NetTracePointProperty mPointProperty[MAX_MODULE_ID_INNER]; /* trace point property include name */

private:
    static NetTrace *gTraceInst;
    static std::mutex gTraceLock;
    static bool gEnableHtrace;
};

class TraceDefer {
public:
    TraceDefer(std::function<void()> beginFunc, std::function<void()> endFunc)
    {
        mBeginFunc = beginFunc;
        mEndFunc = endFunc;
        if (mBeginFunc) {
            mBeginFunc();
        }
    }
    ~TraceDefer()
    {
        if (mEndFunc) {
            mEndFunc();
        }
    }

    // Disable copy and assignment
    TraceDefer(const TraceDefer &) = delete;
    TraceDefer &operator = (const TraceDefer &) = delete;

private:
    std::function<void()> mBeginFunc;
    std::function<void()> mEndFunc;
};

#define DO_TRACE(tracePoint, result)                                                                       \
    uint64_t tpBegin;                                                                                      \
    NetTracePointIdWithLevel level = tracePoint;                                                           \
    std::string name = #tracePoint;                                                                        \
    TraceDefer defer([level, name, &tpBegin]() { TRACE_DELAY_DEFER_BEGIN(level, name.c_str(), tpBegin); }, \
        [level, &result, &tpBegin]() { TRACE_DELAY_DEFER_END(level, (result), tpBegin); })
}
}
#endif // HCOM_TRACE_H
